version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_producao
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - /var/www/public/build
    env_file:
      - .env
